---
title: "School Shooting Analysis"
author: "Omar Souabni"
format: html
editor: visual
---

Load the data

```{r}
load("data/shooting_data.rda")
df<- shooting_data

```

Table of descriptive statistics:

```{r}
library(gtsummary)
tbl_summary(
	data = df,
	by = State,
	include = c(`Killed (includes shooter)`, `Number of Shots Fired`),
	label = list(
		`Killed (includes shooter)` ~ "Killed (includes shooter)",
		`Number of Shots Fired` ~ "Number of Shots Fired"
	),
	missing_text = "Missing"
)
```

Linear regression model:

```{r}
library(broom.helpers)
model <- lm(`Killed (includes shooter)` ~ `State`, data = df)
# Create a regression table using tidy_parameters
regression_table <- tbl_regression(
	model,
	title = "Regression Analysis of Total Fatalities (Including Shooter) by State",
	tidy_fun = broom.helpers::tidy_parameters
)


```

Histogram of 'Killed (includes shooter)

```{r}
library(ggplot2)
ggplot(df, aes(x = `Killed (includes shooter)`)) +
	geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
	labs(title = "Histogram of Killed (includes shooter)",
			 x = "Number of People Killed (including shooter)",
			 y = "Frequency") +
	theme_minimal()
```

Write a function to calculate standard deviation of 'Killed (includes shooter)' for each state

```{r}
library(dplyr)
calculate_sd_per_state <- function(data) {

	result <- data %>%
		group_by(State) %>%
		summarise(SD_Killed = sd(`Killed (includes shooter)`, na.rm = TRUE))


	return(result)
}
# Use the function to calculate standard deviation of 'Killed (includes shooter)' for each state
sd_per_state <- calculate_sd_per_state(df)

print(sd_per_state)
```

p-value of the regression coefficient for Number of Shots Fired


